name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      # - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4.1.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rapi-bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/rapi-bot:latest
            if [ "$(docker ps -q -f name=rapibot)" ]; then
                docker stop rapibot
                docker rm rapibot
            fi
            docker run -d --restart unless-stopped --name rapibot \
              -e WAIFUPORT=${{ secrets.WAIFU_PORT }} \
              -e WAIFUTOKEN=${{ secrets.DISCORD_TOKEN }} \
              -e CATAPI=${{ secrets.CAT_API }} \
              -e CLIENTID=${{ secrets.CLIENT_ID }} \
              ${{ secrets.DOCKER_USERNAME }}/rapi-bot:latest
